import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toaster from "./toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "言葉で遊ぼう",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <link
        rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text x=%2250%%22 y=%2250%%22 style=%22dominant-baseline:central;text-anchor:middle;font-size:90px;%22>🌏</text></svg>"
      />
      <link
        rel="icon alternate"
        type="image/png"
        href="https://twemoji.maxcdn.com/v/13.0.2/72x72/1f30f.png"
      />
      <body className={inter.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
