import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AI } from "./action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Function Calling UI RSC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AI>{children}</AI>
      </body>
    </html>
  );
}

export const runtime = "edge";
